name = "contracking-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
account_id = "e2035d8e0b7173d520ccf643f6f4661c"

routes = [
  { pattern = "contracking-api.dhyegocalota.com.br", custom_domain = true }
]

[[d1_databases]]
binding = "DATABASE"
database_name = "contracking"
database_id = "c7890c46-d847-48e6-90c2-8d1a0c09b6fc"
migrations_dir = "migrations"
